'use strict';
const fs=require('fs'),path=require('path');
const assert=(x,m)=>{if(!x)throw new Error(m)};
const root=path.join(__dirname,'..');
const server=fs.readFileSync(path.join(root,'server.js'),'utf8');
const aluno=fs.readFileSync(path.join(root,'public/aluno.html'),'utf8');
const prof=fs.readFileSync(path.join(root,'public/professor.html'),'utf8');
const qs=require(path.join(root,'questions.json'));
assert(!qs.some(q=>/\b(e-?book|livro|material did[aá]tico|segundo o autor|de acordo com o autor)\b/i.test(q.text)),'source-signaling term');console.log('PASS no e-book/livro/material signaling in questions');
let bad=[];for(const q of qs){const L=q.options.map(x=>x.length),c=L[q.correct],o=L.filter((_,i)=>i!==q.correct),avg=o.reduce((a,b)=>a+b,0)/o.length;if(c>avg*1.4)bad.push(q.id)}assert(!bad.length,'answer length giveaways '+bad.slice(0,8));console.log('PASS correct answer length has no strong giveaway');
assert(server.includes('desired=(G.answerSlots[slotKey]||0)%pairs.length'),'balanced slots');console.log('PASS correct-answer positions rotate evenly');
assert(server.includes('primeiro clique é definitivo')&&aluno.includes('Não é possível alterar'),'immutable answer');console.log('PASS first click locks answer client + server');
assert(server.includes('if(allAnswered)later(()=>finishVote(),650)'),'early finish');console.log('PASS timer skips when all eligible teams answered');
assert(server.includes("}else{for(const [id,r] of Object.entries(payload.results))")&&!server.includes("if(!payload.results[actor.id]?.correct)actor.blocked=true"),'normal miss block');console.log('PASS only Duel loser receives Crunch');
assert(aluno.includes("$('questionText').textContent=v.question?.text"),'student question');console.log('PASS question appears on student control');
assert(prof.includes("includes(p)?(p===30?'🏰'")&&prof.includes(":'?'}"),'hidden icons');console.log('PASS board cells stay ? until revealed');
assert(server.includes('function gateTarget(target,xp)'),'xp gates');console.log('PASS XP gates prevent position outrunning performance');
const pf=qs.filter(q=>q.bank==='pitch-final');assert(pf.length===50&&pf.every(q=>/Greenlight|banca final|playtest|Pitch|júri/i.test(q.text)),'pitch microcases');console.log('PASS Pitch bank uses decision-oriented microcases');
console.log('TOTAL 10/10 CLASSROOM v4.3 SCENARIOS PASS');
